### ISSUE TITLE
Integrate into Homebrew itself

### ISSUE THREAD

**Issue by MikeMcQuaid** [cartr/qt4-autobottler#1]
@cartr Feel free to instaclose this but I saw this repo (thanks @ilovezfs) and thought it would be a cool addition to have some of this stuff be part of https://github.com/homebrew/homebrew-test-bot and https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tap-new.rb and be documented in http://docs.brew.sh/brew-tap.html. We've had requests to document our external tap guide more in https://github.com/Homebrew/brew/issues/2572 and it would be cool to have a fully supported bottling flow on Travis CI for external taps based on what you have here.

**Comment by MikeMcQuaid** [comment]
Also, I just saw this today that may be useful: https://blog.travis-ci.com/2017-05-11-introducing-build-stages?utm_source=broadcast&utm_medium=notification

**Comment by cartr** [comment]
I would definitely appreciate better tap bottling support from core.

**Comment by cartr** [comment]
I would definitely appreciate better tap bottling support from core. In particular, I'd love a single command I could run that detects which formulae have been changed, builds them, uploads them to Bintray, and pushes a commit with the new hashes. (I don't know the extent to which `brew test-bot` already does that.)

The main reason why this is a separate repo rather than just being included in cartr/homebrew-qt4 is to work around the Travis build time limit by submitting multiple build jobs. It would be great if Homebrew could somehow handle that as well, maybe by generating a `.travis.yml` with separate matrix entries for each formula and using the new build stage functionality you mentioned to upload the bottles only when they've been successfully built for every macOS version.

**Comment by MikeMcQuaid** [comment]
> (I don't know the extent to which brew test-bot already does that.)

Yeh, it does all of that. You need to run `brew test-bot` followed by `brew test-bot --ci-upload`. Let me know how/if that works for you.

> maybe by generating a .travis.yml with separate matrix entries for each formula

I think we're unlikely to do this just because it only affects a small subset of formulae (and these are usually not those in third-party taps).

> using the new build stage functionality you mentioned to upload the bottles only when they've been successfully built for every macOS version.

This seems like a good idea. We'd accept PRs to `brew tap-new` to do this. I'm happy to help with usage/docs of this and `brew test-bot`. Would you be interested in working on that? Would love to see your work here end up more widely available.

**Comment by MikeMcQuaid** [comment]
@cartr Any thoughts on this? If you're not 👍, you can just close this out. Thanks!

**Comment by cartr** [comment]
Apologies for not responding to your last comment – I had been planning to take a swing at this, but I unfortunately haven't had as much time to work on Homebrew stuff as I would've liked.

I've actually moved away from using Travis to build homebrew-qt4 due to build time limit issues, but it seems like the work in https://github.com/davidchall/homebrew-hep/pull/114 has gotten a lot further on this than I did.

**Comment by MikeMcQuaid** [comment]
Thanks @cartr!
